package com.java.jhs4.entity;
// Generated 17/02/2016 10:27:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private BigDecimal matricula;
     private Login login;
     private String nombre;
     private String app;
     private String apm;
     private BigDecimal edad;
     private String sexo;
     private Date fechaRegistro;

    public Alumnos() {
    }

    public Alumnos(BigDecimal matricula, Login login, String nombre, String app, String apm, BigDecimal edad, String sexo, Date fechaRegistro) {
       this.matricula = matricula;
       this.login = login;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.edad = edad;
       this.sexo = sexo;
       this.fechaRegistro = fechaRegistro;
    }
   
    public BigDecimal getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(BigDecimal matricula) {
        this.matricula = matricula;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public BigDecimal getEdad() {
        return this.edad;
    }
    
    public void setEdad(BigDecimal edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


