package com.java.jhs4.entity;
// Generated 17/02/2016 10:27:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private BigDecimal idArticulo;
     private String nombre;
     private String descripcion;
     private double costo;
     private double precio;

    public Articulos() {
    }

	
    public Articulos(BigDecimal idArticulo, String nombre, double costo, double precio) {
        this.idArticulo = idArticulo;
        this.nombre = nombre;
        this.costo = costo;
        this.precio = precio;
    }
    public Articulos(BigDecimal idArticulo, String nombre, String descripcion, double costo, double precio) {
       this.idArticulo = idArticulo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costo = costo;
       this.precio = precio;
    }
   
    public BigDecimal getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(BigDecimal idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


